# Buliding my own LinearRegression Model.

## Import library

In [2]:
import numpy as np 
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler ,OneHotEncoder

## data preprocessing.

In [3]:
df = pd.read_csv(r"C:\AI_ML\projects\CarsData.csv")
df.head()

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,Manufacturer
0,I10,2017,7495,Manual,11630,Petrol,145,60.1,1.0,hyundi
1,Polo,2017,10989,Manual,9200,Petrol,145,58.9,1.0,volkswagen
2,2 Series,2019,27990,Semi-Auto,1614,Diesel,145,49.6,2.0,BMW
3,Yeti Outdoor,2017,12495,Manual,30960,Diesel,150,62.8,2.0,skoda
4,Fiesta,2017,7999,Manual,19353,Petrol,125,54.3,1.2,ford

In [4]:
df.drop(columns='model',inplace=True)
df

,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,Manufacturer
0,2017,7495,Manual,11630,Petrol,145,60.1,1.0,hyundi
1,2017,10989,Manual,9200,Petrol,145,58.9,1.0,volkswagen
2,2019,27990,Semi-Auto,1614,Diesel,145,49.6,2.0,BMW
3,2017,12495,Manual,30960,Diesel,150,62.8,2.0,skoda
4,2017,7999,Manual,19353,Petrol,125,54.3,1.2,ford
...,...,...,...,...,...,...,...,...,...
97707,2017,10447,Automatic,8337,Petrol,145,54.3,1.0,ford
97708,2014,14995,Manual,25372,Diesel,30,61.4,2.0,BMW
97709,2017,8950,Manual,19910,Petrol,125,54.3,1.2,ford
97710,2017,10700,Automatic,24468,Petrol,125,50.4,1.4,vauxhall
97711,2019,15798,Manual,10586,Diesel,150,48.7,1.5,vauxhall

In [5]:
x_df = df.drop(['price'],axis=1)
target = df['price']

In [6]:
ohe = OneHotEncoder(handle_unknown='ignore',sparse_output= False)

X_encoded = ohe.fit_transform(x_df[['transmission','fuelType','Manufacturer']])

col_names = ohe.get_feature_names_out(['transmission','fuelType','Manufacturer'])


df_encoded = pd.DataFrame(X_encoded,columns=col_names)


x_numeric = x_df.drop(columns=['transmission','fuelType','Manufacturer'])

final_df = pd.concat([df_encoded, x_numeric.reset_index(drop=True)], axis=1)

x_final = final_df

In [7]:
std = StandardScaler()
data_std = std.fit_transform(x_final)

In [8]:
x_std = pd.DataFrame(data_std,columns=std.get_feature_names_out())
x_std

,transmission_Automatic,transmission_Manual,transmission_Other,transmission_Semi-Auto,fuelType_Diesel,fuelType_Electric,fuelType_Hybrid,fuelType_Other,fuelType_Petrol,Manufacturer_Audi,...,Manufacturer_merc,Manufacturer_skoda,Manufacturer_toyota,Manufacturer_vauxhall,Manufacturer_volkswagen,year,mileage,tax,mpg,engineSize
0,-0.505792,0.872074,-0.009598,-0.543728,-0.839928,-0.007836,-0.179772,-0.050239,0.900047,-0.348184,...,-0.389305,-0.260021,-0.271302,-0.396213,-0.424059,-0.031389,-0.550287,0.392342,0.302466,-1.190382
1,-0.505792,0.872074,-0.009598,-0.543728,-0.839928,-0.007836,-0.179772,-0.050239,0.900047,-0.348184,...,-0.389305,-0.260021,-0.271302,-0.396213,2.358163,-0.031389,-0.665668,0.392342,0.228308,-1.190382
2,-0.505792,-1.146692,-0.009598,1.839155,1.190578,-0.007836,-0.179772,-0.050239,-1.111053,-0.348184,...,-0.389305,-0.260021,-0.271302,-0.396213,-0.424059,0.912609,-1.025863,0.392342,-0.346420,0.599900
3,-0.505792,0.872074,-0.009598,-0.543728,1.190578,-0.007836,-0.179772,-0.050239,-1.111053,-0.348184,...,-0.389305,3.845850,-0.271302,-0.396213,-0.424059,-0.031389,0.367533,0.471260,0.469322,0.599900
4,-0.505792,0.872074,-0.009598,-0.543728,-0.839928,-0.007836,-0.179772,-0.050239,0.900047,-0.348184,...,-0.389305,-0.260021,-0.271302,-0.396213,-0.424059,-0.031389,-0.183587,0.076670,-0.055966,-0.832326
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97707,1.977098,-1.146692,-0.009598,-0.543728,-0.839928,-0.007836,-0.179772,-0.050239,0.900047,-0.348184,...,-0.389305,-0.260021,-0.271302,-0.396213,-0.424059,-0.031389,-0.706644,0.392342,-0.055966,-1.190382
97708,-0.505792,0.872074,-0.009598,-0.543728,1.190578,-0.007836,-0.179772,-0.050239,-1.111053,-0.348184,...,-0.389305,-0.260021,-0.271302,-0.396213,-0.424059,-1.447384,0.102205,-1.422771,0.382804,0.599900
97709,-0.505792,0.872074,-0.009598,-0.543728,-0.839928,-0.007836,-0.179772,-0.050239,0.900047,-0.348184,...,-0.389305,-0.260021,-0.271302,-0.396213,-0.424059,-0.031389,-0.157139,0.076670,-0.055966,-0.832326
97710,1.977098,-1.146692,-0.009598,-0.543728,-0.839928,-0.007836,-0.179772,-0.050239,0.900047,-0.348184,...,-0.389305,-0.260021,-0.271302,2.523894,-0.424059,-0.031389,0.059282,0.076670,-0.296981,-0.474269
97711,-0.505792,0.872074,-0.009598,-0.543728,1.190578,-0.007836,-0.179772,-0.050239,-1.111053,-0.348184,...,-0.389305,-0.260021,-0.271302,2.523894,-0.424059,0.912609,-0.599858,0.471260,-0.402039,-0.295241

In [9]:
x = x_std
y = target

## Spliting the data (70 % fot traaining and 30 % for testing )

In [10]:
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size= 0.3, random_state=42)

## Model building

In [12]:
class LinearRegression:

    def __init__(self,l_t = 1e-1):
        self.w = None
        self.b = 0
        self.l_t = l_t

    # Define gradient.    
    def gradient(self,X,Y):

        y_mean = np.mean(Y)

        prev_cost = float('inf')

        for i in range(5000):

            y_pred = np.dot(X , self.w) + self.b
            
            curr_cost = self.cost(Y , y_pred)

            dw = -(1/self.m) *np.dot(X.T , (Y - y_pred))
            db = -(1/self.m) *np.sum((Y - y_pred))

            self.w = self.w - self.l_t * dw
            self.b = self.b - self.l_t * db

            # To break iteration.
            if (prev_cost - curr_cost) < 1e-6:
                break

            prev_cost = curr_cost

            r2 = 1 - ((np.sum((Y - y_pred) **2 )) / (np.sum((Y - y_mean) **2 )))
            score = 100 * r2

            if i % 10 == 0:
                print(f"iter = {i}, score = {score}, cost= {curr_cost}")
        return score


    # Define a cost fucntion (Root mean square error)
    def cost(self,y_ture,y_pred):
        N = len(y_ture)
        loss = 1/N * np.sqrt(np.sum((y_ture - y_pred) **2 ))
        return loss
    
    
    def fit(self,x,y):

        self.m , self.n = x.shape
        self.w = np.zeros(self.n)

        score =  self.gradient(x,y)

        return score
    
    def score(self , x ,y):
        y_pred = np.dot(x,self.w) + self.b
        y_mean = np.mean(y)
        r2 = 1 - ((np.sum((y - y_pred) **2 )) / (np.sum((y - y_mean) **2 )))
        score = 100 * r2
        return score

    
    def predict(self,x):
        return np.dot(x,self.w) + self.b

In [13]:
model = LinearRegression(1e-2)

In [14]:
model.fit(x_train,y_train)

iter = 0, score = -289.8409077013945, cost= 74.36362581275978
iter = 10, score = -207.13757039542782, cost= 66.00598621130098
iter = 20, score = -147.22698160944265, cost= 59.21950670250214
iter = 30, score = -102.31116936871074, cost= 53.570633514196736
iter = 40, score = -67.74362194510988, cost= 48.7797825704369
iter = 50, score = -40.62592244505658, cost= 44.66317000425977
iter = 60, score = -19.060527718941866, cost= 41.09611364458429
iter = 70, score = -1.745467104508669, cost= 37.990445558961774
iter = 80, score = 12.25087041825017, cost= 35.28078671114753
iter = 90, score = 23.618759421268386, cost= 32.916238926409584
iter = 100, score = 32.883837161226616, cost= 30.85534534998119
iter = 110, score = 40.454664476770965, cost= 29.06301897675172
iter = 120, score = 46.65357683359408, cost= 27.508664392567592
iter = 130, score = 51.7376084724534, cost= 26.165032069218352
iter = 140, score = 55.91327678816832, cost= 25.007527925032235
iter = 150, score = 59.347401768292606, cost= 24.013806457430288
iter = 160, score = 62.17525210492473, cost= 23.163536872970138
iter = 170, score = 64.5068149804332, cost= 22.438268398726244
iter = 180, score = 66.43170198201224, cost= 21.821344876994687
iter = 190, score = 68.02303460546133, cost= 21.29783585595317
iter = 200, score = 69.34054874504658, cost= 20.854464420776896
iter = 210, score = 70.43309093706407, cost= 20.479521956132874
iter = 220, score = 71.34063473603848, cost= 20.162767205945755
iter = 230, score = 72.09591488439646, cost= 19.8953116295872
iter = 240, score = 72.72575493587345, cost= 19.669495517938827
iter = 250, score = 73.25214776513911, cost= 19.478760140588307
iter = 260, score = 73.69313613389974, cost= 19.31752090059232
iter = 270, score = 74.06353103904448, cost= 19.18104557157711
iter = 280, score = 74.37549818554001, cost= 19.065340562859067
iter = 290, score = 74.63903709050803, cost= 18.967047051287498
iter = 300, score = 74.86237267220986, cost= 18.883347870143616
iter = 310, score = 75.0522754450746, cost= 18.81188530910334
iter = 320, score = 75.21432343341066, cost= 18.75068945585319
iter = 330, score = 75.35311648307639, cost= 18.698116372422348
iter = 340, score = 75.47245167706498, cost= 18.652795209827776
iter = 350, score = 75.57546695756874, cost= 18.613583284847028
iter = 360, score = 75.6647587523576, cost= 18.579528138925475
iter = 370, score = 75.7424783404139, cost= 18.549835644294117
iter = 380, score = 75.81041082514692, cost= 18.523843295904566
iter = 390, score = 75.87003987645396, cost= 18.50099791521688
iter = 400, score = 75.92260082572619, cost= 18.48083708335062
iter = 410, score = 75.96912422656762, cost= 18.462973710345906
iter = 420, score = 76.01047160896735, cost= 18.447083230578507
iter = 430, score = 76.04736484005883, cost= 18.432892989817507
iter = 440, score = 76.08041024747469, cost= 18.420173456282846
iter = 450, score = 76.11011845112253, cost= 18.408730946378903
iter = 460, score = 76.13692067736734, cost= 18.398401606021984
iter = 470, score = 76.16118218909418, cost= 18.38904643135062
iter = 480, score = 76.18321335021396, cost= 18.380547148916524
iter = 490, score = 76.20327874918831, cost= 18.372802806021518
iter = 500, score = 76.2216047292679, cost= 18.365726947478045
iter = 510, score = 76.2383856102401, cost= 18.35924527644774
iter = 520, score = 76.25378883501689, cost= 18.353293714800085
iter = 530, score = 76.26795923227941, cost= 18.34781679319614
iter = 540, score = 76.28102255192584, cost= 18.342766313330394
iter = 550, score = 76.29308840185445, cost= 18.338100234875302
iter = 560, score = 76.30425269151343, cost= 18.33378174802333
iter = 570, score = 76.31459966873345, cost= 18.32977849940963
iter = 580, score = 76.32420362086768, cost= 18.326061944876198
iter = 590, score = 76.33313029857217, cost= 18.322606807214537
iter = 600, score = 76.34143811016241, cost= 18.31939062087421
iter = 610, score = 76.34917912595857, cost= 18.316393348792605
iter = 620, score = 76.35639992504576, cost= 18.31359705910838
iter = 630, score = 76.36314231114602, cost= 18.310985651665096
iter = 640, score = 76.36944391959848, cost= 18.308544625975873
iter = 650, score = 76.37533873358674, cost= 18.306260883770733
iter = 660, score = 76.380857524586, cost= 18.3041225604424
iter = 670, score = 76.38602822940075, cost= 18.30211888068871
iter = 680, score = 76.39087627402667, cost= 18.300240034458536
iter = 690, score = 76.3954248528119, cost= 18.29847706997421
iter = 700, score = 76.39969516994746, cost= 18.296821801151946
iter = 710, score = 76.40370664912446, cost= 18.295266727194317
iter = 720, score = 76.40747711621569, cost= 18.29380496250161
iter = 730, score = 76.41102295902908, cost= 18.292430175357044
iter = 740, score = 76.41435926751285, cost= 18.291136534095152
iter = 750, score = 76.41749995723978, cost= 18.289918659673067
iter = 760, score = 76.42045787854205, cost= 18.28877158373846
iter = 770, score = 76.42324491328898, cost= 18.287690711432322
iter = 780, score = 76.4258720609867, cost= 18.286671788284483
iter = 790, score = 76.42834951561863, cost= 18.285710870659283
iter = 800, score = 76.4306867344277, cost= 18.28480429929156
iter = 810, score = 76.43289249966183, cost= 18.283948675522293
iter = 820, score = 76.43497497415235, cost= 18.28314083990077
iter = 830, score = 76.43694175146956, cost= 18.282377852868507
iter = 840, score = 76.43879990129277, cost= 18.28165697728059
iter = 850, score = 76.44055601054492, cost= 18.28097566255403
iter = 860, score = 76.44221622076475, cost= 18.28033153026161
iter = 870, score = 76.44378626212814, cost= 18.279722361013636
iter = 880, score = 76.44527148447547, cost= 18.279146082490843
iter = 890, score = 76.4466768856566, cost= 18.27860075850881
iter = 900, score = 76.44800713746662, cost= 18.27808457900932
iter = 910, score = 76.44926660941157, cost= 18.277595850886758
iter = 920, score = 76.45045939051576, cost= 18.27713298956841
iter = 930, score = 76.45158930935715, cost= 18.27669451127706
iter = 940, score = 76.45265995249673, cost= 18.276279025912245
iter = 950, score = 76.45367468144886, cost= 18.27588523049358
iter = 960, score = 76.45463664832445, cost= 18.27551190311569
iter = 970, score = 76.45554881026425, cost= 18.275157897369503
iter = 980, score = 76.45641394276778, cost= 18.274822137189396
iter = 990, score = 76.457234652013, cost= 18.274503612089703
iter = 1000, score = 76.45801338625178, cost= 18.274201372757744
iter = 1010, score = 76.45875244635857, cost= 18.273914526973684
iter = 1020, score = 76.45945399560223, cost= 18.273642235830245
iter = 1030, score = 76.46012006870397, cost= 18.273383710228057
iter = 1040, score = 76.46075258023933, cost= 18.27313820762434
iter = 1050, score = 76.46135333243619, cost= 18.27290502901485
iter = 1060, score = 76.46192402241671, cost= 18.27268351613073
iter = 1070, score = 76.46246624892659, cost= 18.272473048833422
iter = 1080, score = 76.46298151859125, cost= 18.2722730426924
iter = 1090, score = 76.46347125173567, cost= 18.272082946731686
iter = 1100, score = 76.46393678780056, cost= 18.271902241332302
iter = 1110, score = 76.46437939038604, cost= 18.271730436278897
iter = 1120, score = 76.46480025195011, cost= 18.271567068939763
iter = 1130, score = 76.46520049818838, cost= 18.2714117025703
iter = 1140, score = 76.46558119211777, cost= 18.271263924730825
iter = 1150, score = 76.46594333788683, cost= 18.27112334581033
iter = 1160, score = 76.4662878843319, cost= 18.27098959764851
iter = 1170, score = 76.46661572829808, cost= 18.270862332248818
iter = 1180, score = 76.46692771774153, cost= 18.270741220576195
iter = 1190, score = 76.46722465462913, cost= 18.270625951433235
iter = 1200, score = 76.46750729764975, cost= 18.270516230409314
iter = 1210, score = 76.46777636475036, cost= 18.270411778897454
iter = 1220, score = 76.46803253550956, cost= 18.270312333174292
iter = 1230, score = 76.46827645335976, cost= 18.27021764353855
iter = 1240, score = 76.4685087276684, cost= 18.270127473504143
iter = 1250, score = 76.46872993568823, cost= 18.270041599044
iter = 1260, score = 76.4689406243855, cost= 18.26995980788124
iter = 1270, score = 76.46914131215428, cost= 18.26988189882434
iter = 1280, score = 76.46933249042497, cost= 18.269807681143465
iter = 1290, score = 76.46951462517376, cost= 18.26973697398503
iter = 1300, score = 76.46968815834, cost= 18.26966960582202
iter = 1310, score = 76.46985350915745, cost= 18.26960541393771
iter = 1320, score = 76.47001107540524, cost= 18.269544243940448
iter = 1330, score = 76.47016123458371, cost= 18.269485949307583
iter = 1340, score = 76.47030434502011, cost= 18.269430390956575
iter = 1350, score = 76.47044074690889, cost= 18.269377436841484
iter = 1360, score = 76.47057076329048, cost= 18.269326961573245
iter = 1370, score = 76.47069470097286, cost= 18.269278846062218
iter = 1380, score = 76.47081285139943, cost= 18.269232977181453
iter = 1390, score = 76.47092549146652, cost= 18.269189247449567
iter = 1400, score = 76.47103288429395, cost= 18.269147554731767
iter = 1410, score = 76.4711352799514, cost= 18.269107801958068
iter = 1420, score = 76.47123291614339, cost= 18.269069896857495
iter = 1430, score = 76.47132601885556, cost= 18.26903375170733
iter = 1440, score = 76.47141480296452, cost= 18.268999283096512
iter = 1450, score = 76.47149947281342, cost= 18.268966411702255
iter = 1460, score = 76.47158022275575, cost= 18.268935062079095
iter = 1470, score = 76.47165723766874, cost= 18.268905162459642
iter = 1480, score = 76.47173069343852, cost= 18.268876644566294
iter = 1490, score = 76.47180075741873, cost= 18.268849443433304
iter = 1500, score = 76.47186758886424, cost= 18.268823497238472
iter = 1510, score = 76.47193133934091, cost= 18.268798747144103
iter = 1520, score = 76.47199215311372, cost= 18.268775137146395
iter = 1530, score = 76.4720501675137, cost= 18.26875261393304
iter = 1540, score = 76.47210551328531, cost= 18.2687311267484
iter = 1550, score = 76.47215831491549, cost= 18.26871062726583
iter = 1560, score = 76.47220869094498, cost= 18.26869106946681
iter = 1570, score = 76.47225675426344, cost= 18.268672409526456
iter = 1580, score = 76.472302612389, cost= 18.268654605704967
iter = 1590, score = 76.47234636773322, cost= 18.268637618244842
iter = 1600, score = 76.47238811785215, cost= 18.268621409273397
iter = 1610, score = 76.47242795568454, cost= 18.26860594271034
iter = 1620, score = 76.47246596977755, cost= 18.268591184180117
iter = 1630, score = 76.4725022445011, cost= 18.268577100928784
iter = 1640, score = 76.47253686025095, cost= 18.2685636617451
iter = 1650, score = 76.47256989364172, cost= 18.268550836885694
iter = 1660, score = 76.47260141768977, cost= 18.268538598003996
iter = 1670, score = 76.47263150198718, cost= 18.268526918082777
iter = 1680, score = 76.47266021286656, cost= 18.26851577137011
iter = 1690, score = 76.47268761355794, cost= 18.26850513331853

76.47270863137688

In [15]:
model.score(x_test,y_test)

76.72420135575183

## I got training score = 76.42 and testing score = 76.72